# Generated by Django 6.0.3 on 2026-04-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tecnica", "Técnica"),
                            ("soft", "Soft Skill"),
                            ("linguistica", "Linguística"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("intermedio", "Intermédio"),
                            ("avancado", "Avançado"),
                        ],
                        default="intermedio",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url_perfil", models.URLField(blank=True)),
                ("departamento", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("grau", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=200)),
                ("duracao_anos", models.IntegerField()),
                ("ano_inicio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateField(auto_now_add=True)),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="makingof/")),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("modelacao", "Modelação"),
                            ("implementacao", "Implementação"),
                            ("testes", "Testes"),
                            ("revisao", "Revisão"),
                        ],
                        default="modelacao",
                        max_length=50,
                    ),
                ),
                ("entidade_relacionada", models.CharField(blank=True, max_length=100)),
                (
                    "uso_ia",
                    models.TextField(
                        blank=True, help_text="Descreve como usaste IA (se aplicável)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Making Of",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem"),
                            ("framework", "Framework"),
                            ("ferramenta", "Ferramenta"),
                            ("base_dados", "Base de Dados"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("url_site", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, " Iniciante"),
                            (2, " Básico"),
                            (3, " Intermédio"),
                            (4, " Avançado"),
                            (5, " Expert"),
                        ],
                        default=3,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("certificado_url", models.URLField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("presencial", "Presencial"),
                            ("academico", "Académico"),
                        ],
                        default="online",
                        max_length=50,
                    ),
                ),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="competencias", to="portfolio.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("destaque", models.BooleanField(default=False)),
                ("url_repositorio", models.URLField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano_curricular", models.IntegerField()),
                (
                    "semestre",
                    models.IntegerField(
                        choices=[(1, "1º Semestre"), (2, "2º Semestre")]
                    ),
                ),
                ("ects", models.IntegerField()),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ManyToManyField(
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                ("url_github", models.URLField(blank=True)),
                ("url_video", models.URLField(blank=True)),
                ("conceitos_aplicados", models.TextField(blank=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
