# Generated by Django 6.0.3 on 2026-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("linguagem", "Linguagem"),
                    ("framework", "Framework"),
                    ("ferramenta", "Ferramenta"),
                    ("base_dados", "Base de Dados"),
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("storage", "Storage"),
                    ("outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
